/* Terra 0.4. Links use record identities and explicit snapshot dates, not invented lore. */
function installTerraJourney(api){
  const {$,esc,fold,E}=api;let selected=null,pauseBeforeGuide=false,scope={year:null,polity:null};
  const frame=()=>api.archive()?.d.frames[api.frameIndex()];
  const key=c=>JSON.stringify([c.n,c.c,c.x,c.y]);
  const findCity=(n,p)=>frame()?.set.find(c=>c.n===n&&(p===null||c.c===p));
  const valid=v=>v!==null&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
  const href=(view,data)=>'#'+view+'?'+new URLSearchParams(Object.entries(data).filter(([,v])=>v!==null&&v!==undefined)).toString();
  function scopeText(){const p=api.archive()?.d.frames.flatMap(f=>f.pol).find(p=>p.id===scope.polity);return [p?p.n:scope.polity!==null?'Polity '+scope.polity:'All peoples',scope.year!==null?'through '+E.year(scope.year):'all recorded years'].join(' · ');}
  function panel(id,text){let el=$(id);if(!el){el=document.createElement('div');el.id=id;el.className='journey-context';$(id==='event-context'?'event-list':'people-list').before(el);}el.innerHTML=text?'<span>'+esc(text)+'</span><button data-context-reset="'+(id==='event-context'?'chronicle':'people')+'">Clear filter</button>':'';el.hidden=!text;}
  function beforeRoute(view,params){scope={year:valid(params.get('year')),polity:valid(params.get('polity'))};selected=null;if(view==='people'){const limited=scope.year!==null||scope.polity!==null;$('portrait-grid').classList.toggle('hidden',limited);document.querySelector('#view-people .page-heading p').textContent=limited?'Browse people recorded by the selected year. Later deeds are hidden; the full portrait gallery is available after clearing the filter.':'Eight illustrated biographies, followed by the searchable record of 5,060 notable people.';}panel('event-context',view==='chronicle'&&(scope.year!==null||scope.polity!==null)?'Archive filter: '+scopeText():'');panel('people-context',view==='people'&&(scope.year!==null||scope.polity!==null)?'People born by the selected year: '+scopeText():'');}
  async function afterRoute(view,params){
    if(view!=='atlas'){beforeRoute(view,params);return;}const year=valid(params.get('year'));if(year!==null){const frames=api.archive().d.frames;let ix=0;for(let i=0;i<frames.length;i++)if(frames[i].year<=year)ix=i;api.setFrame(ix);}
    api.world()?.update();onFrame();const name=params.get('city');if(name){const c=findCity(name,valid(params.get('polity')));if(c)selectCity(c,true);else $('place-detail').innerHTML='<h2>Not in this snapshot</h2><p>This settlement is not recorded under the requested identity in '+E.year(frame().year)+'. The archive has not been backfilled.</p>';}
  }
  function onFrame(){if(!frame())return;if(selected&&!frame().set.some(c=>key(c)===key(selected)))selected=null;else if(selected)selected=frame().set.find(c=>key(c)===key(selected));renderSearch();if(selected)showCity(selected);}
  function renderSearch(){const f=frame();if(!f)return;const q=fold($('settlement-search').value);const cities=f.set.map((c,i)=>({...c,_index:i})).filter(c=>!q||fold(c.n).includes(q)).sort((a,b)=>b.p-a.p||a.n.localeCompare(b.n));$('settlement-count').textContent=E.number(cities.length)+' recorded settlements · '+E.year(f.year);$('settlement-results').innerHTML=cities.slice(0,7).map(c=>'<button data-city-index="'+c._index+'"><span>'+esc(c.n)+'</span><small>'+E.short(c.p)+'</small></button>').join('')||'<p>No settlements match this search in this snapshot.</p>';}
  function selectCity(c,focus){selected=c;api.world()?.update();showCity(c);if(focus)api.world()?.focusCell(c.x,c.y);}
  function showCity(c){const f=frame(),p=f.pol.find(p=>p.id===c.c);let visits=api.scenes().map((s,i)=>({s,i})).filter(({s})=>s.name===c.n);$('place-detail').innerHTML='<span class="chip">SETTLEMENT RECORD</span><h2>'+esc(c.n)+'</h2><p>'+esc(E.tr(c.t))+' · '+E.year(f.year)+'</p><div class="detail-stats"><div><span>Population</span><b>'+E.number(c.p)+'</b></div><div><span>People</span><b>'+esc(p?.n||'Polity '+c.c)+'</b></div><div><span>Grid location</span><b>'+c.x+', '+c.y+'</b></div></div><div class="journey-links"><a href="'+esc(href('chronicle',{year:f.year,polity:c.c}))+'">This people’s chronicle ↗</a><a href="'+esc(href('people',{year:f.year,polity:c.c}))+'">Recorded lives ↗</a>'+visits.map(({s,i})=>'<a class="journey-enter" href="#walk/'+i+'">Enter the '+E.year(s.year)+' walk ↗</a>').join('')+'</div><p class="quiet-note">Population and location come from this snapshot. Only three settlements have a walkable reconstruction; entering one opens its stated year.</p>';}
  function pickCell(x,y){const f=frame();if(!f)return false;const matches=f.set.filter(c=>c.x===x&&c.y===y).sort((a,b)=>b.p-a.p);if(!matches.length){const had=!!selected;selected=null;if(had)api.world()?.update();return false;}selectCity(matches[0],false);return true;}
  function polityLinks(p){const target=$('place-detail');target.insertAdjacentHTML('beforeend','<div class="journey-links"><a href="'+esc(href('chronicle',{polity:p.id,year:frame().year}))+'">Read this chronicle ↗</a><a href="'+esc(href('people',{polity:p.id,year:frame().year}))+'">Browse recorded lives ↗</a></div>');}
  function paintCities(ctx,f,w,h){ctx.save();const centers=new Map();for(const c of f.set){const k=c.x+':'+c.y;if(!centers.has(k)||centers.get(k).p<c.p)centers.set(k,c);}for(const c of centers.values()){const x=(c.x+.5)*w/180,y=(c.y+.5)*h/90,r=Math.min(4.1,1.35+Math.log10(Math.max(1,c.p))*.31);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle='#edd09a';ctx.fill();ctx.lineWidth=1.1;ctx.strokeStyle='#132c32';ctx.stroke();}if(selected){const x=(selected.x+.5)*w/180,y=(selected.y+.5)*h/90;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.strokeStyle='#fff0c7';ctx.lineWidth=2;ctx.stroke();}ctx.restore();}
  function acceptEvent(e){return (scope.polity===null||e.p===scope.polity)&&(scope.year===null||e.yr<=scope.year);}
  function acceptPerson(p){return (scope.polity===null||p.p===scope.polity)&&(scope.year===null||p.b<=scope.year);}
  function lifeLabel(p){return scope.year!==null&&p.d>scope.year?'Born '+E.year(p.b)+' · Later life hidden after '+E.year(scope.year):E.year(p.b)+' to '+E.year(p.d)+' · Recorded age '+p.a;}
  function visibleDeeds(p){return p.deeds.filter(d=>scope.year===null||d[0]<=scope.year);}
  function decorateBiography(p){const box=$('person-detail .bio-content')||document.querySelector('#person-detail .bio-content');if(box&&scope.year!==null)box.insertAdjacentHTML('beforeend','<p class="quiet-note">Role, era and disposition are whole-life archive summaries, not the person’s state at this cutoff. Birth and deed dates are filtered.</p>');if(box)box.insertAdjacentHTML('beforeend','<div class="journey-links"><a href="'+esc(href('chronicle',{polity:p.p,year:scope.year}))+'">Explore this people’s records ↗</a></div>');}
  async function fieldGuide(){
    const index=Math.max(0,Math.min(2,Number($('walk-scene').value)||0)),play=await api.preparePlay(),sc=play.scenes[index],a=api.archive(),f=a.d.frames.filter(f=>f.year<=sc.year).at(-1),c=f.set.find(c=>c.n===sc.name&&c.c===sc.pid),recent=api.events().filter(e=>e.p===sc.pid&&e.yr<=sc.year).slice(0,6);
    if(api.active()!=='walk')return;pauseBeforeGuide=!!api.walkState()?.paused;api.sendWalk({type:'terra:pause',value:true});const dlg=$('field-guide');$('field-guide-content').innerHTML='<div class="eyebrow">FIELD GUIDE · PRESERVED WORLD RECORD</div><h2>'+esc(sc.name)+'</h2><p class="guide-meta">'+E.year(sc.year)+' · '+esc(sc.polity)+' · '+esc(sc.biome_ru)+'</p><div class="guide-facts"><div><b>'+E.number(sc.pop)+'</b><span>settlement population in the model</span></div><div><b>'+sc.npcs.length+'</b><span>reconstructed residents in this walk</span></div></div><p>'+esc(sc.desc)+'</p><div class="journey-links">'+(c?'<a href="'+esc(href('atlas',{year:sc.year,city:c.n,polity:c.c}))+'">Locate this settlement on the atlas ↗</a>':'<span>No matching settlement record in this snapshot.</span>')+'<a href="'+esc(href('chronicle',{polity:sc.pid,year:sc.year}))+'">Open this people’s chronicle ↗</a></div><h3>Recent records of '+esc(sc.polity)+'</h3><p class="quiet-note">These events concern the people as a whole, not necessarily this town. No event below is later than the walk’s year.</p>'+recent.map(e=>'<div class="guide-event"><span>'+E.year(e.yr)+'</span><p>'+esc(e.text)+'</p></div>').join('')+'<p class="quiet-note">The archive is selective. Architecture, scenery and walking residents are interpretations. The walk is paused while this guide is open.</p>';
    dlg.showModal();
  }
  function mount(){
    const inspector=document.querySelector('.inspector');const box=document.createElement('section');box.className='settlement-finder';box.innerHTML='<label class="field-label" for="settlement-search">Find a settlement</label><input id="settlement-search" type="search" placeholder="Search names in this snapshot…" autocomplete="off"><p id="settlement-count"></p><div id="settlement-results"></div>';
    inspector.insertBefore(box,$('place-detail'));$('settlement-search').addEventListener('input',renderSearch);
    const tray=document.createElement('div');tray.className='journey-tray';tray.innerHTML='<span>THREE PLACES IN TIME</span>'+api.scenes().map((s,i)=>'<a href="'+esc(href('atlas',{year:s.year,city:s.name}))+'">'+esc(s.name)+' <small>'+E.year(s.year)+'</small></a>').join('');document.querySelector('.map-layout').before(tray);
    const note=document.createElement('span');note.className='map-key';note.textContent='Gold dots: recorded settlement cells';document.querySelector('.map-top').append(note);
    const btn=document.createElement('button');btn.id='open-field-guide';btn.className='square guide-trigger';btn.textContent='Guide';btn.setAttribute('aria-label','Open this settlement’s field guide');$('walk-fullscreen').before(btn);btn.onclick=()=>fieldGuide().catch(api.fail);
    const dlg=document.createElement('dialog');dlg.id='field-guide';dlg.innerHTML='<button id="close-field-guide" class="dialog-close" aria-label="Close field guide">×</button><div id="field-guide-content"></div>';document.body.append(dlg);$('close-field-guide').onclick=()=>dlg.close();dlg.addEventListener('close',()=>{if(api.active()==='walk')api.sendWalk({type:'terra:pause',value:pauseBeforeGuide});});dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close();});
    document.addEventListener('click',e=>{const city=e.target.closest('[data-city-index]');if(city){const c=frame()?.set[Number(city.dataset.cityIndex)];if(c)selectCity(c,true);}const reset=e.target.closest('[data-context-reset]');if(reset)location.hash=reset.dataset.contextReset;const link=e.target.closest('a[href^="#"]');if(link){$('person-dialog').close();dlg.close();}});
  }
  const previousCityPanel=showCity;showCity=function(c){previousCityPanel(c);if(c.n==='Níhmīwū'&&c.c===294&&frame().year===500)document.querySelector('#place-detail .journey-links')?.insertAdjacentHTML('afterbegin','<a class="journey-enter" href="#courtyard">New market courtyard · 500 CE ↗</a>');};
  mount();return {clearCity:()=>selected=null,beforeRoute,afterRoute,onFrame,pickCell,polityLinks,paintCities,acceptEvent,acceptPerson,lifeLabel,visibleDeeds,decorateBiography,fieldGuide,inspect:()=>({selectedCity:selected?{name:selected.n,polity:selected.c,x:selected.x,y:selected.y,year:frame().year}:null,scope:{...scope},settlements:frame()?.set.length||0})};
}
