/* Terra 0.4 scenery. Presentation only: no changes to simulation, terrain heights or street endpoints. */
function terraScene04(){
  terraPaths=function(){
    var isStone=S.id==='capital',rng=mulberry(S.seed*1501+4),texture=isStone?terraCanvas(512,function(ctx,n){ctx.fillStyle='#958f80';ctx.fillRect(0,0,n,n);for(var row=-1;row<13;row++)for(var k=-1;k<12;k++){var x=k*52+(row%2)*26,y=row*44,v=174+rng()*26;ctx.fillStyle='rgb('+v+','+(v*.97)+','+(v*.89)+')';ctx.beginPath();ctx.roundRect(x+1.4,y+1.4,49,41,3+rng()*2);ctx.fill();for(var j=0;j<14;j++){ctx.fillStyle='#34382e10';ctx.fillRect(x+rng()*48,y+rng()*40,1+rng()*3,1);}}}):groundTexture();texture.repeat.set(1,1);
    var mat=new THREE.MeshStandardMaterial({map:texture,color:isStone?'#d5c9aa':'#bda982',roughness:1,vertexColors:true,transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});
    var pos=[],uv=[],colors=[],indices=[],tint=new THREE.Color();
    function vert(x,z,alpha){pos.push(x,groundH(x,z)+.035,z);uv.push(x/3.5,z/3.5);tint.setScalar(.96+.04*Math.sin(x*.4+z*.53));colors.push(tint.r,tint.g,tint.b,alpha);return pos.length/3-1;}
    function tri(a,b,c){var ax=pos[b*3]-pos[a*3],az=pos[b*3+2]-pos[a*3+2],bx=pos[c*3]-pos[a*3],bz=pos[c*3+2]-pos[a*3+2];if(az*bx-ax*bz>0)indices.push(a,b,c);else indices.push(a,c,b);}
    for(var road of S.streets){var [x1,z1,x2,z2]=road,dx=x2-x1,dz=z2-z1,len=Math.hypot(dx,dz);if(len<1)continue;var nx=-dz/len,nz=dx/len,steps=Math.ceil(len/2),base=pos.length/3,width=isStone?3.6:3.9;
      for(var j=0;j<=steps;j++){var t=j/steps,offset=Math.sin(t*Math.PI)*Math.sin(t*7+S.seed)*.3,w=width*(1+.07*Math.sin(t*11));for(var across of [-1,-.78,0,.78,1]){var x=x1+dx*t+nx*(offset+across*w*.5),z=z1+dz*t+nz*(offset+across*w*.5);vert(x,z,Math.abs(across)>.9?0:isStone?.94:.58);}}
      for(var j=0;j<steps;j++)for(var k=0;k<4;k++){var b=base+j*5+k;tri(b,b+1,b+5);tri(b+1,b+6,b+5);}
    }
    if(S.pois.plaza){var [px,pz]=S.pois.plaza,base=pos.length/3,segments=96,radius=isStone?15:10;for(var ring of [0,.35,.72,1,1.12])for(var j=0;j<=segments;j++){var a=j/segments*Math.PI*2,r=radius*ring*(1+.07*Math.sin(a*3+.2)+.04*Math.cos(a*7)),alpha=ring>1?0:isStone?.92:.52;vert(px+Math.cos(a)*r,pz+Math.sin(a)*r,alpha);}for(var ring=0;ring<4;ring++)for(var j=0;j<segments;j++){var b=base+ring*(segments+1)+j;tri(b,b+1,b+segments+1);tri(b+1,b+segments+2,b+segments+1);}}
    var geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,4));geo.setIndex(indices);geo.computeVertexNormals();var mesh=new THREE.Mesh(geo,mat);mesh.receiveShadow=true;mesh.renderOrder=1;mesh.name='Terra04 feathered paths';R3.scene.add(mesh);GAME.paths04={streetSegments:S.streets.length,vertices:pos.length/3,featheredEdges:true,plazaShape:'irregular radial'};
  };
  function facades04(){
    var rng=mulberry(19031+S.seed),bag=new Bag(),wood=col('#6d5039'),dark=col('#332c25'),stone=col('#bbac8e'),count=0;
    for(var b of S.buildings){var [kind,x,z,rot,sx,sz,h]=b;if(!['house','house2'].includes(kind))continue;var y=groundH(x,z),ca=Math.cos(rot),sa=Math.sin(rot),trim=colVar(rng,S.id==='bronze'?'#c5a679':'#d5c5a6',.09);
      function part(c,lx,ly,lz,w,hh,d){bag.put(PRIM.box,c,x+ca*lx+sa*lz,y+ly,z-sa*lx+ca*lz,0,rot,0,w,hh,d);count++;}
      var face=sz*.5+.055,doorW=Math.min(1.25,sx*.17),doorH=Math.min(2.1,h*.67);part(dark,0,doorH*.5,face,doorW,doorH,.07);
      part(wood,-doorW*.55,doorH*.5,face+.05,.12,doorH+.15,.15);part(wood,doorW*.55,doorH*.5,face+.05,.12,doorH+.15,.15);part(wood,0,doorH+.08,face+.07,doorW+ .34,.16,.21);
      for(var plank=0;plank<5;plank++)part(colVar(rng,'#6a4c34',.15),(plank-2)*doorW*.185,doorH*.5,face+.045,doorW*.17,doorH*.97,.08);
      part(stone,0,.08,face+.17,doorW+.48,.16,.52);var floors=kind==='house2'?2:1;
      for(var level=0;level<floors;level++)for(var side of [-1,1]){var wx=side*sx*.3,wy=h*.6+level*h*.77,w=Math.min(.92,sx*.14),hh=Math.min(.96,h*.28);part(dark,wx,wy,face,w,hh,.08);for(var s of [-1,1]){part(trim,wx+s*(w*.5+.06),wy,face+.07,.12,hh+.2,.2);part(wood,wx+s*w*.72,wy,face+.06,w*.37,hh,.12);}part(trim,wx,wy-hh*.5-.09,face+.13,w+ .3,.18,.32);part(wood,wx,wy,face+.07,.04,hh,.10);part(wood,wx,wy,face+.07,w,.04,.10);}
      part(trim,0,.2,sz*.5+.05,sx+.1,.4,.16);part(trim,0,.2,-sz*.5-.05,sx+.1,.4,.16);
    }
    var mesh=bag.mesh(new THREE.MeshStandardMaterial({vertexColors:true,roughness:.96}));mesh.castShadow=true;mesh.receiveShadow=true;mesh.name='Terra04 window and door joinery';R3.scene.add(mesh);GAME.facadeDetails=count;
  }
  function clouds04(){
    var mat=R3.sky.material;if(!mat.fragmentShader.includes('gl_FragColor=vec4(c,1.0);'))return;
    mat.uniforms.terraCloudTime={value:0};mat.fragmentShader='uniform float terraCloudTime;\nfloat tcHash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}\nfloat tcNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(tcHash(i),tcHash(i+vec2(1.,0.)),f.x),mix(tcHash(i+vec2(0.,1.)),tcHash(i+vec2(1.)),f.x),f.y);}\n'+mat.fragmentShader;
    mat.fragmentShader=mat.fragmentShader.replace('gl_FragColor=vec4(c,1.0);','vec2 cu=vP.xz/max(.12,vP.y)*2.4+vec2(terraCloudTime,0.);float cn=.6*tcNoise(cu)+.27*tcNoise(cu*2.07)+.13*tcNoise(cu*4.03);float ca=smoothstep(.53,.70,cn)*smoothstep(.025,.24,vP.y);c=mix(c,mix(hor,vec3(.88,.87,.81),.53)*max(.17,min(1.,glow)),ca*.50);gl_FragColor=vec4(c,1.0);');mat.needsUpdate=true;GAME.clouds04=true;
  }
  var waypoint04=null,landmarks04=[],guide04=null;
  function jump04(id){var lm=landmarks04.find(x=>x.id===id);if(!lm)return false;var candidate=null;
    for(var r of [7,12,18,24,32]){for(var i=0;i<20;i++){var a=i/20*Math.PI*2,x=lm.x+Math.cos(a)*r,z=lm.z+Math.sin(a)*r;if(Math.abs(x)>580||Math.abs(z)>580||groundH(x,z)<WATER_Y+.15)continue;var q=pushOut(x,z,.6);if(Math.hypot(q[0]-x,q[1]-z)<.02){candidate=[x,z];break;}}if(candidate)break;}
    if(!candidate)return false;terraClearKeys();GAME.teleport(candidate[0],candidate[1],Math.atan2(candidate[0]-lm.x,candidate[1]-lm.z));G.pitch=-.04;waypoint04=lm;return true;
  }
  function controls04(){
    var known=[['plaza','Town center'],['market','Market'],['temple',S.id==='neolithic'?'Ancestral pillars':'Sanctuary'],['gate','Main gate'],['shore','Shore'],['jetty','Landing stage']];
    for(var [id,label]of known){var p=id==='gate'?S.pois.gates?.[0]:S.pois[id];if(p)landmarks04.push({id,label,x:p[0],z:p[1]});}
    var style=document.createElement('style');style.textContent='#places04{position:fixed;right:24px;top:113px;z-index:26;padding:8px 13px;background:#112932df;border:1px solid #d4c49870;color:#fff0d3;border-radius:5px;font-size:11px}#landmarks04{width:min(450px,90vw);max-height:85vh;background:#102832;color:#eee4ce;border:1px solid #d5c09088;padding:24px;box-sizing:border-box}#landmarks04::backdrop{background:#041216ba}#landmarks04 h2{font:29px Georgia;margin:0 0 12px}#landmarks04 p{font-size:12px;color:#a9c0bd;line-height:1.6}#landmarks04 .stop04{display:flex;gap:7px;margin:9px 0}#landmarks04 button{font:12px system-ui;padding:11px;background:#1b3943;border:1px solid #d5c09045;color:#ebdcc1;cursor:pointer;border-radius:3px}#landmarks04 .mark04{flex:1;text-align:left}#landmarks04 .jump04{color:#ead19c}#waypoint04{position:fixed;left:50%;bottom:64px;transform:translateX(-50%);z-index:25;display:flex;align-items:center;gap:10px;padding:9px 12px;background:#112c35e8;border:1px solid #bda66f80;max-width:80%;font:11px system-ui;color:#eddab0}#waypoint04[hidden]{display:none}#waypoint04 small{display:block;font-size:9px;color:#b6cbc4;margin-top:3px}#waypoint04 button{background:transparent;color:#eee;border:0;font-size:20px}#bearing04{display:block;font-size:20px}.terra-touch-active #places04{top:100px;right:12px}.terra-touch-active #waypoint04{bottom:163px}@media(max-height:430px){.terra-touch-active #waypoint04{bottom:20px;max-width:42%;font-size:10px}.terra-touch-active #places04{top:101px}}';document.head.append(style);
    var btn=document.createElement('button');btn.id='places04';btn.textContent='Places';btn.setAttribute('aria-label','Choose a local landmark');document.body.append(btn);
    guide04=document.createElement('dialog');guide04.id='landmarks04';guide04.innerHTML='<h2>Find your way.</h2><p>Mark a destination for a straight-line bearing, or jump to a checked landing spot nearby. This does not calculate a walking route.</p>'+landmarks04.map(l=>'<div class="stop04"><button class="mark04" data-mark04="'+l.id+'">'+l.label+'</button><button class="jump04" data-jump04="'+l.id+'">Jump</button></div>').join('')+'<button id="close-places04">Back to the walk</button>';document.body.append(guide04);
    var indicator=document.createElement('div');indicator.id='waypoint04';indicator.hidden=true;indicator.innerHTML='<span id="bearing04">↑</span><div><span id="waypoint-text04"></span><small>Straight-line distance</small></div><button id="clear-waypoint04" aria-label="Clear destination">×</button>';document.body.append(indicator);
    btn.onclick=()=>{terraPause(true);guide04.showModal();};guide04.addEventListener('close',()=>terraPause(false));document.getElementById('close-places04').onclick=()=>guide04.close();document.getElementById('clear-waypoint04').onclick=()=>waypoint04=null;
    guide04.addEventListener('click',e=>{var mark=e.target.closest('[data-mark04]'),jump=e.target.closest('[data-jump04]');if(mark){waypoint04=landmarks04.find(l=>l.id===mark.dataset.mark04);guide04.close();}if(jump){if(jump04(jump.dataset.jump04))guide04.close();else e.target.textContent='No clear landing';}});
  }
  var previousBuild04=buildWorld,previousLoop04=loop,previousInspect04=GAME.inspect,nextLabel04=0,disposed04=false;
  buildWorld=function(){previousBuild04();facades04();clouds04();controls04();GAME.ready=true;};
  loop=function(ts){if(!G||!G.on)return;previousLoop04(ts);if(G.paused)return;if(R3.sky.material.uniforms.terraCloudTime)R3.sky.material.uniforms.terraCloudTime.value=G.el*.004;
    if(ts>=nextLabel04){nextLabel04=ts+150;var el=document.getElementById('waypoint04');if(el){el.hidden=!waypoint04;if(waypoint04){var dx=waypoint04.x-G.player.x,dz=waypoint04.z-G.player.z,dist=Math.hypot(dx,dz),bearing=Math.atan2(-dx,-dz)-G.yaw;document.getElementById('waypoint-text04').textContent=waypoint04.label+' · '+Math.round(dist)+' m'+(dist<8?' · Arrived':'');document.getElementById('bearing04').style.transform='rotate('+(-bearing)+'rad)';}}}
  };
  function dispose04(){if(disposed04||!R3)return;disposed04=true;G.on=false;G.paused=false;GAME.ready=false;var geometries=new Set(),materials=new Set(),textures=new Set();R3.scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)for(var m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);});for(var m of materials){for(var value of Object.values(m))if(value?.isTexture)textures.add(value);if(m.uniforms)for(var u of Object.values(m.uniforms))if(u.value?.isTexture)textures.add(u.value);}for(var t of textures)t.dispose();for(var g of geometries)g.dispose();for(var m of materials)m.dispose();R3.renderer.dispose();}
  window.addEventListener('message',e=>{if(e.source!==parent||!e.data)return;if(e.data.type==='terra:site'){e.stopImmediatePropagation();jump04(e.data.site);}if(e.data.type==='terra:stop')dispose04();},true);
  GAME.dispose=dispose04;GAME.jumpToLandmark=jump04;GAME.localLandmarks=()=>landmarks04.map(l=>({...l}));GAME.inspect=function(){return {...previousInspect04(),version:'0.4.0',paths04:GAME.paths04,facadeDetails:GAME.facadeDetails,clouds04:!!GAME.clouds04,waypoint:waypoint04?{...waypoint04,distance:Math.hypot(waypoint04.x-G.player.x,waypoint04.z-G.player.z)}:null,disposed:disposed04};};
}
